const photoA="https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80";
const photoB="https://images.unsplash.com/photo-1590644365607-1c5a38e6b568?auto=format&fit=crop&w=900&q=80";
const photoC="https://images.unsplash.com/photo-1517581177682-a085bb7ffb15?auto=format&fit=crop&w=900&q=80";
const specialties=["Drenagem","Terraplenagem","Estruturas","Documental","Pavimentação","Obras Complementares"];
const defaultUsers=[
 {id:1,name:"Thyago Pinheiro Viégas Mendonça",email:"thyago.viegas@vale.com",company:"FICO",role:"Administrador",authProvider:"local",globalApproval:true,specialties:[],active:true},
 {id:2,name:"Carlos Mendes",email:"fiscal@fico.com.br",company:"FICO",role:"Fiscal FICO",globalApproval:false,specialties:["Drenagem","Terraplenagem"],active:true},
 {id:3,name:"Marina Costa",email:"gestor@fico.com.br",company:"FICO",role:"Gestor FICO",globalApproval:true,specialties:[],active:true},
 {id:4,name:"Roberto Lima",email:"contratada@empa.com.br",company:"EMPA",role:"Contratada",globalApproval:false,specialties:[],active:true},
 {id:5,name:"Fernanda Soave",email:"fernanda@fico.com.br",company:"FICO",role:"Fiscal FICO",globalApproval:false,specialties:["Estruturas","Documental"],active:true}
];
const defaultIssues=[
 {id:1901,company:"EMPA",asset:"A47",segment:"1.6",km:"35+074 a 35+080",type:"Drenagem",classification:"Tipo A",description:"Drenagem obstruída por acúmulo de material no lado esquerdo.",deadline:"2026-07-08",status:"Aguardando validação",owner:"Carlos Mendes",contractor:"Roberto Lima",before:photoA,after:photoB,history:["Pendência registrada por Ana Souza","Correção enviada por Roberto Lima"]},
 {id:1902,company:"ATERPA",asset:"C10",segment:"1.4A",km:"87+775 a 87+949",type:"Terraplenagem",classification:"Tipo A",description:"Falhas na proteção vegetal e erosão superficial no talude.",deadline:"2026-07-10",status:"Em tratamento",owner:"Carlos Mendes",contractor:"Equipe Qualidade",before:photoC,after:null,history:["Pendência registrada por Carlos Mendes"]},
 {id:1903,company:"APIA",asset:"OAE Córrego Baldaia",segment:"2.2",km:"100+085 a 100+292",type:"Estruturas",classification:"Tipo B",description:"Melhorias necessárias no acabamento do concreto aparente do pilar.",deadline:"2026-07-15",status:"Aguardando validação",owner:"Fernanda Soave",contractor:"Almiro Marques",before:photoB,after:photoA,history:["Pendência registrada por Fernanda Soave","Evidência de correção recebida"]},
 {id:1904,company:"GSA",asset:"C43",segment:"1.3",km:"46+066 a 46+176",type:"Documental",classification:"Tipo B",description:"Databook de montagem pendente de complementação.",deadline:"2026-07-18",status:"Aberta",owner:"Fernanda Soave",contractor:"Qualidade",before:photoA,after:null,history:["Pendência registrada por Fernanda Soave"]},
 {id:1905,company:"EMPA",asset:"A06",segment:"1.5",km:"71+122 a 71+718",type:"Drenagem",classification:"Tipo A",description:"Dispositivo de drenagem superficial não executado conforme projeto.",deadline:"2026-06-30",status:"Rejeitada",owner:"Carlos Mendes",contractor:"Roberto Lima",before:photoC,after:photoB,history:["Pendência registrada","Correção enviada","Correção rejeitada: limpeza incompleta"]},
 {id:1906,company:"ATERPA",asset:"A03",segment:"1.2",km:"30+903 a 31+045",type:"Pavimentação",classification:"Tipo C",description:"Regularização localizada da camada de acabamento.",deadline:"2026-07-04",status:"Baixada",owner:"Marina Costa",contractor:"Equipe Produção",before:photoA,after:photoC,history:["Pendência registrada","Correção enviada","Baixa aprovada por Marina Costa"]}
];

const state={users:JSON.parse(localStorage.getItem("atlas-users")||"null")||defaultUsers,issues:JSON.parse(localStorage.getItem("atlas-issues")||"null")||defaultIssues,currentUser:null};
const API_ENABLED=location.protocol==="http:"||location.protocol==="https:";let apiToken=localStorage.getItem("atlas-api-token"),result;
async function api(path,options={}){if(window.AtlasOffline&&!['/login','/logout','/change-password'].includes(path))return AtlasOffline.request(path,options,apiToken);const response=await fetch(`/api${path}`,{...options,headers:{"Content-Type":"application/json",...(apiToken?{"Authorization":`Bearer ${apiToken}`}:{}) ,...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Não foi possível concluir a operação");return body}
async function updateSyncStatus(){const element=$("#syncStatus");if(!element||!window.AtlasOffline)return;const pending=await AtlasOffline.count();element.className=`sync-status ${navigator.onLine?(pending?"pending":"online"):"offline"}`;element.querySelector("strong").textContent=navigator.onLine?(pending?`${pending} aguardando envio`:"Sincronizado"):`Offline · ${pending} pendente${pending===1?"":"s"}`}
async function syncNow(){if(!API_ENABLED||!apiToken||!window.AtlasOffline)return;const result=await AtlasOffline.flush(apiToken);await updateSyncStatus();if(result.sent){await hydrateFromApi();renderAll();toast(`${result.sent} registro${result.sent===1?"":"s"} sincronizado${result.sent===1?"":"s"}.`)}}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("Não foi possível ler a imagem"));reader.readAsDataURL(file)})}
function mapApiIssue(i){const opening=(i.evidence||[]).find(e=>e.kind==="ABERTURA"),correction=[...(i.evidence||[])].reverse().find(e=>e.kind==="CORRECAO");return {id:i.id,company:i.company,asset:i.asset,segment:i.segment||"",kmStart:i.km_start||"",kmEnd:i.km_end||"",km:[i.km_start,i.km_end].filter(Boolean).join(" a ")||"Não informado",type:i.specialty,classification:i.classification,description:i.description,deadline:(i.deadline_at||i.opened_at||"").slice(0,10),status:i.status,owner:i.fico_owner||"Não atribuído",contractor:i.contractor_owner||"Não atribuído",before:opening?`/${opening.file_path}`:photoA,after:correction?`/${correction.file_path}`:null,history:(i.history||[]).map(h=>h.comment?`${h.event}: ${h.comment}`:h.event)}}
async function hydrateFromApi(){const issues=await api("/issues");state.issues=issues.map(mapApiIssue);if(state.currentUser.role==="Administrador"){const users=await api("/users");state.users=users.map(u=>({id:u.id,name:u.name,email:u.email,company:u.company,role:u.role,globalApproval:!!u.global_approval,specialties:[],active:!!u.active}))}}
async function prepareOffline(){if(!navigator.onLine){toast("Conecte-se à internet para atualizar o pacote offline.");return}const button=$("#prepareOfflineBtn");button.disabled=true;button.textContent="Preparando...";try{await hydrateFromApi();const urls=[...new Set(state.issues.flatMap(i=>[i.before,i.after]).filter(url=>url&&url.startsWith("/uploads/")))];for(const url of urls){try{await fetch(url)}catch{}}renderAll();toast(`${state.issues.length} pendências preparadas para uso offline.`)}finally{button.disabled=false;button.textContent="Preparar offline"}}
const initialAdmin=state.users.find(u=>u.id===1);if(initialAdmin){initialAdmin.name="Thyago Pinheiro Viégas Mendonça";initialAdmin.email="thyago.viegas@vale.com";initialAdmin.company="FICO";initialAdmin.role="Administrador";initialAdmin.authProvider="local";initialAdmin.globalApproval=true;initialAdmin.active=true;localStorage.setItem("atlas-users",JSON.stringify(state.users))}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const save=()=>{localStorage.setItem("atlas-users",JSON.stringify(state.users));localStorage.setItem("atlas-issues",JSON.stringify(state.issues))};
const initials=n=>n.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase();
const statusClass=s=>({"Aberta":"aberta","Em tratamento":"tratamento","Aguardando validação":"validacao","Baixada":"baixada","Rejeitada":"rejeitada"}[s]||"aberta");
const formatDate=d=>new Intl.DateTimeFormat("pt-BR").format(new Date(`${d}T12:00:00`));
const canApprove=i=>state.currentUser&&(state.currentUser.globalApproval||state.currentUser.specialties.includes(i.type));
const canSubmitCorrection=i=>state.currentUser&&state.currentUser.role==="Contratada"&&state.currentUser.company===i.company&&["Aberta","Em tratamento","Rejeitada"].includes(i.status);
function flowStepper(status){const steps=["Pendência aberta","Correção informada","Validação FICO","Baixa concluída"];const current={"Aberta":0,"Em tratamento":0,"Rejeitada":0,"Aguardando validação":2,"Baixada":3}[status]??0;return `<div class="flow-stepper">${steps.map((s,k)=>`<div class="flow-step ${k<current?"done":k===current?"current":""}">${s}</div>`).join("")}</div>`}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.remove("hidden");setTimeout(()=>t.classList.add("hidden"),2600)}

async function login(email){
 const password=$("#loginPassword").value;
 let user,result;
 if(API_ENABLED){
  try{result=await api("/login",{method:"POST",body:JSON.stringify({email,password})});await AtlasOffline.provisionIdentity(email,password,result.user,result.token)}
  catch(error){if(navigator.onLine)throw error;result=await AtlasOffline.offlineLogin(email,password)}
  apiToken=result.token;localStorage.setItem("atlas-api-token",apiToken);
  user={...result.user,globalApproval:result.user.global_approval,mustChangePassword:result.user.must_change_password,company:result.user.company,specialties:result.user.specialties||[]};
  state.currentUser=user;
 }else{
  user=state.users.find(u=>u.email===email&&u.active);
  if(!user)throw new Error("Usuário não encontrado ou inativo.");
  if(user.id===1&&password!=="Atlas@2026")throw new Error("Senha inválida.");
  state.currentUser=user;
 }
 $("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");
 $("#sidebarName").textContent=user.name;$("#sidebarRole").textContent=user.role;$("#sidebarAvatar").textContent=initials(user.name);
 $$('.admin-only').forEach(el=>el.classList.toggle("hidden",user.role!=="Administrador"));
 if(API_ENABLED&&user.mustChangePassword&&!result?.offline){$("#passwordDialog").showModal();return}
 if(API_ENABLED)await hydrateFromApi();
 renderAll();showView("dashboard");await updateSyncStatus();if(navigator.onLine)syncNow();
}
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();try{await login($("#loginEmail").value)}catch(error){toast(error.message)}});$$('[data-demo]').forEach(b=>b.addEventListener("click",()=>{$("#loginEmail").value=b.dataset.demo}));$("#logoutBtn").addEventListener("click",async()=>{if(API_ENABLED&&apiToken&&navigator.onLine){try{await api("/logout",{method:"POST",body:"{}"})}catch{}}localStorage.removeItem("atlas-api-token");location.reload()});

function showView(view){$$('.view').forEach(v=>v.classList.remove("active-view"));$(`#${view}View`).classList.add("active-view");$$('.nav-item').forEach(n=>n.classList.toggle("active",n.dataset.view===view));const titles={dashboard:["Visão geral","Painel operacional"],issues:["Carteira unificada","Pendências"],approvals:["Fila de trabalho","Aprovações"],users:["Administração","Gestão de usuários"]};$("#pageEyebrow").textContent=titles[view][0];$("#pageTitle").textContent=titles[view][1];if(innerWidth<760)$(".sidebar").classList.remove("open")}
$$('.nav-item').forEach(n=>n.addEventListener("click",()=>showView(n.dataset.view)));$$('[data-go]').forEach(n=>n.addEventListener("click",()=>showView(n.dataset.go)));$("#menuBtn").addEventListener("click",()=>$(".sidebar").classList.toggle("open"));

function renderExecutiveDashboard(){const container=$("#executiveDashboard"),isAdmin=state.currentUser.role==="Administrador";container.classList.toggle("hidden",!isAdmin);if(!isAdmin)return;const filter=$("#executiveCompanyFilter"),selected=filter.value,companies=[...new Set(state.issues.map(i=>i.company))].sort();filter.innerHTML='<option value="">Todas as empresas</option>'+companies.map(c=>`<option value="${c}" ${c===selected?"selected":""}>${c}</option>`).join("");const portfolio=state.issues.filter(i=>!filter.value||i.company===filter.value),total=portfolio.length,closed=portfolio.filter(i=>i.status==="Baixada").length,open=total-closed,overdue=portfolio.filter(i=>i.status!=="Baixada"&&new Date(`${i.deadline}T12:00:00`)<new Date("2026-07-11T12:00:00")).length,approval=portfolio.filter(i=>i.status==="Aguardando validação").length,rejected=portfolio.filter(i=>i.status==="Rejeitada").length,rate=total?Math.round(closed/total*100):0;$("#executiveMetrics").innerHTML=`<div class="executive-kpi"><small>Carteira total</small><strong>${total}</strong><span>pendências no recorte</span></div><div class="executive-kpi"><small>Backlog ativo</small><strong>${open}</strong><span>ainda não baixadas</span></div><div class="executive-kpi"><small>Em atraso</small><strong>${overdue}</strong><span>prazo ultrapassado</span></div><div class="executive-kpi"><small>Aguardando fiscal</small><strong>${approval}</strong><span>prontas para validar</span></div><div class="executive-kpi"><small>Taxa de baixa</small><strong>${rate}%</strong><span>${closed} concluída(s)</span></div>`;
 const companyRows=companies.map(c=>{const rows=state.issues.filter(i=>i.company===c),done=rows.filter(i=>i.status==="Baixada").length,pct=Math.round(done/rows.length*100);return `<div class="performance-row"><span>${c}</span><div class="performance-track"><span style="width:${pct}%"></span></div><strong>${pct}%</strong></div>`}).join("");$("#companyPerformance").innerHTML=companyRows;
 const types=[...new Set(portfolio.map(i=>i.type))].map(type=>({type,count:portfolio.filter(i=>i.type===type&&i.status!=="Baixada").length})).sort((a,b)=>b.count-a.count),maxType=Math.max(1,...types.map(x=>x.count));$("#typePerformance").innerHTML=types.map(x=>`<div class="performance-row"><span>${x.type}</span><div class="performance-track"><span style="width:${x.count/maxType*100}%"></span></div><strong>${x.count}</strong></div>`).join("")||'<p class="muted">Sem dados no recorte.</p>';
 $("#bottleneckList").innerHTML=`<div class="bottleneck"><div class="bottleneck-icon">!</div><div><h4>Prazos vencidos</h4><p>Demandam plano de ação</p></div><strong>${overdue}</strong></div><div class="bottleneck"><div class="bottleneck-icon">✓</div><div><h4>Fila de validação</h4><p>Aguardando fiscal habilitado</p></div><strong>${approval}</strong></div><div class="bottleneck"><div class="bottleneck-icon">↻</div><div><h4>Correções rejeitadas</h4><p>Retornaram à contratada</p></div><strong>${rejected}</strong></div>`}

function renderDashboard(){renderExecutiveDashboard();const counts={open:state.issues.filter(i=>i.status==="Aberta").length,treatment:state.issues.filter(i=>i.status==="Em tratamento"||i.status==="Rejeitada").length,approval:state.issues.filter(i=>i.status==="Aguardando validação").length,closed:state.issues.filter(i=>i.status==="Baixada").length};$("#summaryGrid").innerHTML=`<article class="metric"><div class="metric-head"><span>Abertas</span><i class="metric-icon">○</i></div><strong>${counts.open}</strong><small><b>1.806</b> na base para migração</small></article><article class="metric"><div class="metric-head"><span>Em tratamento</span><i class="metric-icon">↻</i></div><strong>${counts.treatment}</strong><small>Com a contratada</small></article><article class="metric"><div class="metric-head"><span>Aguardando validação</span><i class="metric-icon">✓</i></div><strong>${counts.approval}</strong><small>Na fila dos fiscais</small></article><article class="metric"><div class="metric-head"><span>Baixadas</span><i class="metric-icon">↓</i></div><strong>${counts.closed}</strong><small>Com histórico completo</small></article>`;
 const attention=state.issues.filter(i=>i.status!=="Baixada").slice(0,4);$("#attentionList").innerHTML=attention.map(i=>`<button class="issue-row text-btn" data-issue="${i.id}"><img class="issue-thumb" src="${i.before}" alt="Evidência da pendência"><div style="text-align:left"><h4>#${i.id} · ${i.type}</h4><p>${i.asset} · ${i.company} · prazo ${formatDate(i.deadline)}</p></div><span class="status ${statusClass(i.status)}">${i.status}</span></button>`).join("");
 const statuses=["Aberta","Em tratamento","Aguardando validação","Rejeitada","Baixada"];const colors=["#f89b32","#3578bc","#6fa2d2","#b7403b","#18324d"];$("#statusChart").innerHTML=statuses.map((s,k)=>{const n=state.issues.filter(i=>i.status===s).length;return `<div class="chart-row"><span>${s}</span><strong>${n}</strong><div class="chart-track"><span style="width:${n/state.issues.length*100}%;background:${colors[k]}"></span></div></div>`}).join("");
 $("#activityList").innerHTML=state.issues.slice(0,3).map((i,k)=>`<div class="activity"><div class="activity-icon">${k===0?"✓":k===1?"↻":"+"}</div><div><p><strong>${i.history.at(-1)}</strong><br>na pendência #${i.id}</p><small>Hoje, ${9+k}:2${k}</small></div></div>`).join("");bindIssueLinks()}

function renderIssues(){const statuses=[...new Set(state.issues.map(i=>i.status))],types=[...new Set(state.issues.map(i=>i.type))];$("#statusFilter").innerHTML='<option value="">Todos os status</option>'+statuses.map(x=>`<option>${x}</option>`).join("");$("#typeFilter").innerHTML='<option value="">Todos os tipos</option>'+types.map(x=>`<option>${x}</option>`).join("");filterIssues()}
function filterIssues(){const q=$("#issueSearch").value.toLowerCase(),s=$("#statusFilter").value,t=$("#typeFilter").value;const rows=state.issues.filter(i=>(!q||JSON.stringify(i).toLowerCase().includes(q))&&(!s||i.status===s)&&(!t||i.type===t));$("#issuesTable").innerHTML=rows.map(i=>`<tr class="clickable" data-issue="${i.id}"><td><strong>#${i.id}</strong><small>${i.classification}</small></td><td><strong>${i.type}</strong><small>${i.description.slice(0,58)}${i.description.length>58?"…":""}</small></td><td><strong>${i.asset}</strong><small>${i.km}</small></td><td>${i.company}</td><td>${formatDate(i.deadline)}</td><td><span class="status ${statusClass(i.status)}">${i.status}</span></td><td><button class="row-action">Abrir</button></td></tr>`).join("");bindIssueLinks()}
[$("#issueSearch"),$("#statusFilter"),$("#typeFilter")].forEach(el=>el.addEventListener(el.tagName==="INPUT"?"input":"change",filterIssues));

function renderApprovals(){const eligible=state.issues.filter(i=>i.status==="Aguardando validação"&&(state.currentUser.role==="Administrador"||canApprove(i)));$("#approvalNotice").innerHTML=state.currentUser.globalApproval?"Você possui <strong>aprovação geral</strong> e pode validar qualquer tipo de pendência.":`Sua alçada atual: <strong>${state.currentUser.specialties.join(", ")||"sem especialidades de aprovação"}</strong>.`;$("#approvalCards").innerHTML=eligible.length?eligible.map(i=>`<article class="approval-card"><div class="approval-images"><div><img src="${i.before}" alt="Foto antes"><span>Antes</span></div><div><img src="${i.after}" alt="Foto depois"><span>Depois</span></div></div><div class="approval-body"><span class="status ${statusClass(i.status)}">${i.classification}</span><h3>#${i.id} · ${i.type}</h3><p>${i.description}</p><div class="approval-meta">${i.asset} · ${i.company} · ${i.km}</div><div class="approval-actions"><button class="btn danger" data-reject="${i.id}">Rejeitar</button><button class="btn primary" data-approve="${i.id}">Aprovar baixa</button></div></div></article>`).join(""):'<div class="panel"><h3>Fila concluída</h3><p class="muted">Não há pendências aguardando sua validação.</p></div>';$$('[data-approve]').forEach(b=>b.onclick=()=>decide(+b.dataset.approve,true));$$('[data-reject]').forEach(b=>b.onclick=()=>decide(+b.dataset.reject,false))}
async function completeDecision(id,approved,comment=""){const i=state.issues.find(x=>x.id===id);if(!canApprove(i)&&state.currentUser.role!=="Administrador"){throw new Error("Seu perfil não possui alçada para esta pendência.")}if(API_ENABLED){const response=await api(`/issues/${id}/decision`,{method:"POST",body:JSON.stringify({decision:approved?"approve":"reject",comment})});if(response.queued){i.status=approved?"Baixada":"Rejeitada";i.history.push(`${approved?"Baixa aguardando sincronização":"Rejeição aguardando sincronização"}: ${comment}`)}else await hydrateFromApi()}else{i.status=approved?"Baixada":"Rejeitada";i.history.push(`${approved?"Baixa aprovada":"Correção rejeitada"} por ${state.currentUser.name}${comment?`: ${comment}`:""}`);save()}renderAll();await updateSyncStatus();toast(navigator.onLine?(approved?`Pendência #${id} baixada com sucesso.`:`Pendência #${id} devolvida à contratada.`):"Operação salva no aparelho e aguardando conexão.")}
async function decide(id,approved){if(!approved){$("#decisionForm").elements.issueId.value=id;$("#decisionDialog").showModal();return}try{await completeDecision(id,true)}catch(error){toast(error.message)}}

function renderUsers(){$("#usersTable").innerHTML=state.users.map(u=>`<tr><td><div style="display:flex;gap:10px;align-items:center"><div class="avatar">${initials(u.name)}</div><div><strong>${u.name}</strong><small>${u.email}</small></div></div></td><td>${u.company}</td><td>${u.role}</td><td class="permission-list">${u.globalApproval?'<strong>Aprovação geral</strong>':(u.specialties||[]).join(", ")||"Sem permissão de baixa"}</td><td><span class="status ${u.active?"baixada":"rejeitada"}">${u.active?"Ativo":"Inativo"}</span></td><td><button class="toggle-status" data-user="${u.id}">${u.active?"Desativar":"Ativar"}</button></td></tr>`).join("");$$('[data-user]').forEach(b=>b.onclick=async()=>{const u=state.users.find(x=>x.id===+b.dataset.user);if(u.id===state.currentUser.id){toast("Não é possível desativar o próprio usuário.");return}try{if(API_ENABLED)await api(`/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({active:!u.active})});u.active=!u.active;if(!API_ENABLED)save();renderUsers();toast(`Usuário ${u.active?"ativado":"desativado"}.`)}catch(error){toast(error.message)}})}

function bindIssueLinks(){$$('[data-issue]').forEach(el=>el.onclick=e=>{if(e.target.closest("[data-approve],[data-reject]"))return;const issue=state.issues.find(i=>i.id===+el.dataset.issue);openIssue(issue.id);if(state.currentUser.role==="Administrador")addAdminEditAction(issue)})}
function addAdminEditAction(issue){const actions=document.createElement("div");actions.className="drawer-actions admin-edit-actions";actions.innerHTML='<button class="btn ghost" type="button">Editar dados, responsáveis e fotos</button>';actions.querySelector("button").onclick=()=>openEditIssue(issue);$("#issueDrawerContent").append(actions)}
function openEditIssue(issue){closeDrawer();const form=$("#editIssueForm");form.elements.issueId.value=issue.id;form.elements.company.value=issue.company;form.elements.classification.value=issue.classification;form.elements.specialty.value=issue.type;form.elements.asset.value=issue.asset;form.elements.ficoOwner.value=issue.owner==="Não atribuído"?"":issue.owner;form.elements.contractorOwner.value=issue.contractor==="Não atribuído"?"":issue.contractor;form.elements.deadlineAt.value=issue.deadline||"";form.elements.kmStart.value=issue.kmStart||"";form.elements.kmEnd.value=issue.kmEnd||"";form.elements.description.value=issue.description;$("#editIssueDialog").showModal()}
function openIssue(id){const i=state.issues.find(x=>x.id===id);const auth=canApprove(i)||state.currentUser.role==="Administrador";const submit=canSubmitCorrection(i);$("#issueDrawerContent").innerHTML=`<div class="drawer-head"><div><p class="eyebrow">Pendência #${i.id}</p><h2>${i.type}</h2><span class="status ${statusClass(i.status)}">${i.status}</span></div><button class="icon-btn" id="closeDrawer">×</button></div><div class="drawer-body">${flowStepper(i.status)}<img class="drawer-cover" src="${i.before}" alt="Foto inicial da pendência"><div class="detail-grid"><div class="detail-item"><small>Empresa</small><strong>${i.company}</strong></div><div class="detail-item"><small>Classificação</small><strong>${i.classification}</strong></div><div class="detail-item"><small>Ativo e segmento</small><strong>${i.asset} · ${i.segment}</strong></div><div class="detail-item"><small>Localização</small><strong>${i.km}</strong></div><div class="detail-item"><small>Prazo</small><strong>${formatDate(i.deadline)}</strong></div><div class="detail-item"><small>Fiscal responsável</small><strong>${i.owner}</strong></div></div><h3>Descrição</h3><p class="muted">${i.description}</p><h3>Histórico</h3><div class="timeline">${i.history.map((h,k)=>`<div class="timeline-item"><h4>${h}</h4><p>${k?"Hoje":"10/07/2026"} · Registro auditado</p></div>`).join("")}</div></div>${submit?`<div class="drawer-actions"><button class="btn primary" id="drawerCorrection">Informar correção e enviar foto</button></div>`:""}${i.status==="Aguardando validação"&&auth?`<div class="drawer-actions"><button class="btn danger" id="drawerReject">Rejeitar</button><button class="btn primary" id="drawerApprove">Aprovar baixa</button></div>`:""}`;$("#drawerOverlay").classList.remove("hidden");$("#issueDrawer").classList.remove("hidden");$("#closeDrawer").onclick=closeDrawer;if($("#drawerCorrection"))$("#drawerCorrection").onclick=()=>openCorrection(i);if($("#drawerApprove"))$("#drawerApprove").onclick=()=>{decide(id,true);closeDrawer()};if($("#drawerReject"))$("#drawerReject").onclick=()=>{decide(id,false);closeDrawer()}}
function closeDrawer(){$("#drawerOverlay").classList.add("hidden");$("#issueDrawer").classList.add("hidden")}$("#drawerOverlay").onclick=closeDrawer;
function openCorrection(issue){closeDrawer();const form=$("#correctionForm");form.elements.issueId.value=issue.id;$("#correctionSummary").innerHTML=`<strong>Pendência #${issue.id} · ${issue.type}</strong><br>${issue.asset} · ${issue.company} · ${issue.km}`;$("#correctionDialog").showModal()}
$$('.close-correction-dialog').forEach(b=>b.onclick=()=>$("#correctionDialog").close());
$("#correctionForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),issue=state.issues.find(i=>i.id===+f.get("issueId"));try{if(API_ENABLED){const file=e.target.elements.photo.files[0],response=await api(`/issues/${issue.id}/correction`,{method:"POST",body:JSON.stringify({comment:f.get("comment"),photo_name:file.name,photo_data_url:await fileToDataUrl(file),captured_at:new Date().toISOString()})});if(response.queued){issue.after=URL.createObjectURL(file);issue.status="Aguardando validação";issue.history.push(`Correção salva offline por ${state.currentUser.name}`)}else await hydrateFromApi()}else{issue.after=photoB;issue.status="Aguardando validação";issue.history.push(`Correção informada por ${state.currentUser.name}: ${f.get("comment")}`);save()}e.target.reset();$("#correctionDialog").close();renderAll();await updateSyncStatus();showView("issues");toast(navigator.onLine?`Correção da pendência #${issue.id} enviada para validação.`:"Correção salva no aparelho e aguardando conexão.")}catch(error){toast(error.message)}};

$("#newIssueBtn").onclick=()=>$("#issueDialog").showModal();$$('.close-dialog').forEach(b=>b.onclick=()=>$("#issueDialog").close());$("#issueForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{let id;if(API_ENABLED){const file=e.target.elements.photo.files[0],response=await api("/issues",{method:"POST",body:JSON.stringify({company:f.get("company"),asset:f.get("asset"),specialty:f.get("type"),classification:f.get("classification"),description:f.get("description"),km_start:f.get("kmStart"),km_end:f.get("kmEnd"),deadline_at:f.get("deadline"),opened_at:new Date().toISOString().slice(0,10),fico_owner:f.get("ficoOwner"),photo_name:file.name,photo_data_url:await fileToDataUrl(file),captured_at:new Date().toISOString()})});id=response.id||response.temp_id;if(response.queued)state.issues.unshift({id,company:f.get("company"),asset:f.get("asset"),segment:"A definir",km:`${f.get("kmStart")} a ${f.get("kmEnd")}`,type:f.get("type"),classification:f.get("classification"),description:f.get("description"),deadline:f.get("deadline"),status:"Aberta",owner:f.get("ficoOwner"),contractor:"Não atribuído",before:URL.createObjectURL(file),after:null,history:[`Pendência registrada offline por ${state.currentUser.name}`]});else await hydrateFromApi()}else{id=Math.max(...state.issues.map(i=>i.id))+1;state.issues.unshift({id,company:f.get("company"),asset:f.get("asset"),segment:"A definir",km:`${f.get("kmStart")} a ${f.get("kmEnd")}`,type:f.get("type"),classification:f.get("classification"),description:f.get("description"),deadline:f.get("deadline"),status:"Aberta",owner:f.get("ficoOwner"),contractor:"Não atribuído",before:photoA,after:null,history:[`Pendência registrada por ${state.currentUser.name}`]});save()}e.target.reset();$("#issueDialog").close();renderAll();await updateSyncStatus();showView("issues");toast(navigator.onLine?`Pendência #${id} registrada.`:"Pendência salva no aparelho e aguardando conexão.")}catch(error){toast(error.message)}};
$("#specialtyChecks").innerHTML=specialties.map(s=>`<label><input type="checkbox" name="specialty" value="${s}">${s}</label>`).join("");$("#newUserBtn").onclick=()=>$("#userDialog").showModal();$$('.close-user-dialog').forEach(b=>b.onclick=()=>$("#userDialog").close());$("#userForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(state.users.some(u=>u.email===f.get("email"))){toast("Já existe um usuário com este e-mail.");return}try{if(API_ENABLED){await api("/users",{method:"POST",body:JSON.stringify({name:f.get("name"),email:f.get("email"),company:f.get("company"),role:f.get("role"),global_approval:f.get("globalApproval")==="on",specialties:f.getAll("specialty"),temporary_password:f.get("temporaryPassword")})});await hydrateFromApi()}else{state.users.push({id:Date.now(),name:f.get("name"),email:f.get("email"),company:f.get("company"),role:f.get("role"),globalApproval:f.get("globalApproval")==="on",specialties:f.getAll("specialty"),active:true});save()}e.target.reset();$("#userDialog").close();renderUsers();toast("Usuário cadastrado com senha temporária.")}catch(error){toast(error.message)}};

$$('.close-decision-dialog').forEach(b=>b.onclick=()=>$("#decisionDialog").close());$("#decisionForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await completeDecision(+f.get("issueId"),false,f.get("comment"));e.target.reset();$("#decisionDialog").close()}catch(error){toast(error.message)}};

$("#passwordForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),next=f.get("newPassword");if(next!==f.get("confirmPassword")){toast("A confirmação não corresponde à nova senha.");return}try{await api("/change-password",{method:"POST",body:JSON.stringify({current_password:f.get("currentPassword"),new_password:next})});await AtlasOffline.clearIdentity(state.currentUser.email);localStorage.removeItem("atlas-api-token");toast("Senha alterada. Entre novamente com a nova senha.");setTimeout(()=>location.reload(),1400)}catch(error){toast(error.message)}};

$$('.close-edit-dialog').forEach(b=>b.onclick=()=>$("#editIssueDialog").close());$("#editIssueForm").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),id=+f.get("issueId"),issue=state.issues.find(i=>i.id===id);try{if(API_ENABLED){await api(`/issues/${id}`,{method:"PATCH",body:JSON.stringify({company:f.get("company"),classification:f.get("classification"),specialty:f.get("specialty"),asset:f.get("asset"),fico_owner:f.get("ficoOwner"),contractor_owner:f.get("contractorOwner"),deadline_at:f.get("deadlineAt")||null,km_start:f.get("kmStart"),km_end:f.get("kmEnd"),description:f.get("description")})});const file=e.target.elements.historicalPhoto.files[0];if(file)await api(`/issues/${id}/evidence`,{method:"POST",body:JSON.stringify({kind:f.get("evidenceKind"),photo_name:file.name,photo_data_url:await fileToDataUrl(file),captured_at:new Date().toISOString()})});await hydrateFromApi()}else{issue.company=f.get("company");issue.classification=f.get("classification");issue.type=f.get("specialty");issue.asset=f.get("asset");issue.owner=f.get("ficoOwner")||"Não atribuído";issue.contractor=f.get("contractorOwner")||"Não atribuído";issue.deadline=f.get("deadlineAt");issue.kmStart=f.get("kmStart");issue.kmEnd=f.get("kmEnd");issue.km=[issue.kmStart,issue.kmEnd].filter(Boolean).join(" a ");issue.description=f.get("description");issue.history.push(`Pendência editada por ${state.currentUser.name}`);save()}e.target.reset();$("#editIssueDialog").close();renderAll();showView("issues");toast("Pendência e responsabilidades atualizadas.")}catch(error){toast(error.message)}};

$("#executiveCompanyFilter").addEventListener("change",renderExecutiveDashboard);
$("#prepareOfflineBtn").addEventListener("click",prepareOffline);
function renderAll(){renderDashboard();renderIssues();renderApprovals();renderUsers()}
if(window.AtlasOffline){AtlasOffline.register();addEventListener("online",syncNow);addEventListener("offline",updateSyncStatus);addEventListener("atlas-sync-change",updateSyncStatus);addEventListener("atlas-sync-complete",updateSyncStatus)}

let installPrompt;
const installButton=$("#installAppBtn");
const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);
const isStandalone=matchMedia("(display-mode: standalone)").matches||navigator.standalone===true;
addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;installButton.classList.remove("hidden")});
if(isIos&&!isStandalone)installButton.classList.remove("hidden");
installButton.addEventListener("click",async()=>{
 if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.classList.add("hidden");return}
 if(isIos){toast("No Safari, toque em Compartilhar e depois em Adicionar à Tela de Início.");return}
 toast("Abra o menu do navegador e selecione Instalar aplicativo.");
});
addEventListener("appinstalled",()=>{installButton.classList.add("hidden");toast("ATLAS instalado com sucesso.")});
