(function(){
  const DB_NAME="atlas-offline-v1",DB_VERSION=2;
  function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;if(!database.objectStoreNames.contains("cache"))database.createObjectStore("cache",{keyPath:"key"});if(!database.objectStoreNames.contains("outbox"))database.createObjectStore("outbox",{keyPath:"id",autoIncrement:true});if(!database.objectStoreNames.contains("identity"))database.createObjectStore("identity",{keyPath:"email"});if(!database.objectStoreNames.contains("idmap"))database.createObjectStore("idmap",{keyPath:"tempId"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function transaction(store,mode,action){const database=await openDb();return new Promise((resolve,reject)=>{const tx=database.transaction(store,mode),object=tx.objectStore(store),request=action(object);tx.oncomplete=()=>resolve(request?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
  const cachePut=(key,value)=>transaction("cache","readwrite",s=>s.put({key,value,updatedAt:new Date().toISOString()}));
  async function cacheGet(key){const value=await transaction("cache","readonly",s=>s.get(key));return value?.value}
  async function saveIdMap(tempId,serverId){await transaction("idmap","readwrite",s=>s.put({tempId,serverId,createdAt:new Date().toISOString()}))}
  async function resolvePath(path){const match=path.match(/^\/issues\/(-\d+)\/(correction|decision)$/);if(!match)return path;const mapping=await transaction("idmap","readonly",s=>s.get(+match[1]));if(!mapping)throw new Error(`A abertura ${match[1]} ainda precisa ser sincronizada`);return `/issues/${mapping.serverId}/${match[2]}`}
  async function resolveIssueId(id){if(id>=0)return id;const mapping=await transaction("idmap","readonly",s=>s.get(id));return mapping?.serverId||id}
  function uuid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
  async function enqueue(path,options){const body=options.body?JSON.parse(options.body):{};body.sync_id=body.sync_id||uuid();const record={syncId:body.sync_id,path,method:options.method||"POST",body,createdAt:new Date().toISOString(),attempts:0};const id=await transaction("outbox","readwrite",s=>s.add(record));dispatchEvent(new CustomEvent("atlas-sync-change"));return {queued:true,offline:true,sync_id:body.sync_id,temp_id:-id}}
  async function allOutbox(){return (await transaction("outbox","readonly",s=>s.getAll()))||[]}
  async function deleteOutbox(id){await transaction("outbox","readwrite",s=>s.delete(id));dispatchEvent(new CustomEvent("atlas-sync-change"))}
  async function updateOutbox(item){item.attempts=(item.attempts||0)+1;item.lastAttemptAt=new Date().toISOString();await transaction("outbox","readwrite",s=>s.put(item))}
  async function count(){return (await transaction("outbox","readonly",s=>s.count()))||0}
  function compressDataUrl(dataUrl){return new Promise((resolve,reject)=>{if(!dataUrl||dataUrl.length<4000000)return resolve(dataUrl);const image=new Image();image.onload=()=>{try{const max=1920,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.round(image.naturalWidth*scale);canvas.height=Math.round(image.naturalHeight*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.8))}catch(error){reject(error)}};image.onerror=()=>reject(new Error("Foto offline inválida"));image.src=dataUrl})}
  async function request(path,options,token){const method=(options.method||"GET").toUpperCase(),headers={"Content-Type":"application/json",...(token?{"Authorization":`Bearer ${token}`}:{})};if(method==="GET"){try{const response=await fetch(`/api${path}`,{...options,headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||"Falha na consulta")}const body=await response.json();await cachePut(path,body);return body}catch(error){const cached=await cacheGet(path);if(cached!==undefined)return cached;throw error}}
    const offlineAllowed=method==="POST"&&(path==="/issues"||/\/issues\/-?\d+\/(correction|decision)$/.test(path));if(!navigator.onLine){if(offlineAllowed)return enqueue(path,options);throw new Error("Esta operação administrativa exige conexão")}
    try{const response=await fetch(`/api${path}`,{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Não foi possível concluir a operação");return body}catch(error){if(offlineAllowed&&error instanceof TypeError)return enqueue(path,options);throw error}}
  async function flush(token){if(!navigator.onLine||!token)return {sent:0,pending:await count()};let sent=0,lastError="";for(const item of await allOutbox()){try{if(item.body?.photo_data_url)item.body.photo_data_url=await compressDataUrl(item.body.photo_data_url);const path=await resolvePath(item.path),response=await fetch(`/api${path}`,{method:item.method,headers:{"Content-Type":"application/json","Authorization":`Bearer ${token}`},body:JSON.stringify(item.body)}),body=await response.json().catch(()=>({}));if(response.ok){if(item.path==="/issues"&&body.id)await saveIdMap(-item.id,body.id);await deleteOutbox(item.id);sent++}else{lastError=body.error||body.detail||`HTTP ${response.status}`;item.lastError=lastError;await updateOutbox(item);if(response.status===401||response.status===403)break}}catch(error){lastError=error.message||"Falha de rede";item.lastError=lastError;await updateOutbox(item);break}}const pending=await count();dispatchEvent(new CustomEvent("atlas-sync-complete",{detail:{sent,pending,error:lastError}}));return {sent,pending,error:lastError}}
  async function passwordVerifier(password,salt){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:150000,hash:"SHA-256"},material,256);return btoa(String.fromCharCode(...new Uint8Array(bits)))}
  async function provisionIdentity(email,password,user,token){const salt=crypto.getRandomValues(new Uint8Array(16)),verifier=await passwordVerifier(password,salt);await transaction("identity","readwrite",s=>s.put({email:email.toLowerCase(),salt:Array.from(salt),verifier,user,token,validUntil:new Date(Date.now()+7*86400000).toISOString()}))}
  async function offlineLogin(email,password){const identity=await transaction("identity","readonly",s=>s.get(email.toLowerCase()));if(!identity||new Date(identity.validUntil)<new Date())throw new Error("Este dispositivo precisa se conectar para renovar o acesso offline");const verifier=await passwordVerifier(password,new Uint8Array(identity.salt));if(verifier!==identity.verifier)throw new Error("E-mail ou senha inválidos");return {token:identity.token,user:identity.user,offline:true}}
  async function clearIdentity(email){await transaction("identity","readwrite",s=>s.delete(email.toLowerCase()))}
  async function register(){if("serviceWorker" in navigator&&location.protocol.startsWith("http")){try{let refreshing=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!refreshing){refreshing=true;location.reload()}});const registration=await navigator.serviceWorker.register("/service-worker.js?v=16",{updateViaCache:"none"});await registration.update()}catch{}}}
  window.AtlasOffline={request,flush,count,pending:allOutbox,resolveIssueId,cachePut,cacheGet,provisionIdentity,offlineLogin,clearIdentity,register};
})();
